import type { BlockCategory } from '../engine/FilterRule';

export const FILTER_LIST_CATEGORIES: BlockCategory[] = ['ads', 'tracker', 'malware', 'phishing'];

export interface FilterListMeta {
  id: string;
  name: string;
  url: string;
  category: BlockCategory;
  enabled: boolean;
  lastUpdated: string | null;
  ruleCount: number;
  cosmeticCount?: number;
  version: string | null;
  checksum: string | null;
  sizeBytes: number;
  builtIn: boolean;
  /** Pro abonelere özel liste (free kullanıcılar etkinleştiremez). */
  pro?: boolean;
  /** Zayıf benchmark kategorisine yönelik ek etiket (örn. 'cookie-notices'). */
  subCategory?: string;
}

export const DEFAULT_FILTER_LISTS: FilterListMeta[] = [
  {
    id: 'adguard-base',
    name: 'AdGuard Base',
    url: 'https://filters.adtidy.org/extension/ublock/filters/2.txt',
    category: 'ads',
    enabled: true,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
  },
  {
    id: 'easylist',
    name: 'EasyList',
    url: 'https://easylist.to/easylist/easylist.txt',
    category: 'ads',
    enabled: true,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
  },
  {
    id: 'easyprivacy',
    name: 'EasyPrivacy',
    url: 'https://easylist.to/easylist/easyprivacy.txt',
    category: 'tracker',
    enabled: true,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
  },
  {
    id: 'adguard-tracking',
    name: 'AdGuard Tracking Protection',
    url: 'https://filters.adtidy.org/extension/ublock/filters/3.txt',
    category: 'tracker',
    enabled: true,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
  },
  {
    id: 'malware-domains',
    name: 'Malware Protection',
    url: 'https://raw.githubusercontent.com/StevenBlack/hosts/master/data/stevenblack/hosts',
    category: 'malware',
    enabled: true,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
  },
{
    id: 'phishing-domains',
    name: 'Phishing Protection',
    url: 'https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/ALL-phishing-domains.txt',
    category: 'phishing',
    enabled: true,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
  },
  {
    id: 'adguard-urlparams',
    name: 'AdGuard URL Tracking Protection',
    url: 'https://filters.adtidy.org/extension/ublock/filters/17.txt',
    category: 'tracker',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    subCategory: 'url-tracking',
  },
  {
    id: 'adguard-cookie-notices',
    name: 'AdGuard Cookie Notices',
    url: 'https://filters.adtidy.org/extension/ublock/filters/20.txt',
    category: 'tracker',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    subCategory: 'cookie-notices',
  },
  {
    id: 'adguard-social',
    name: 'AdGuard Social Media',
    url: 'https://filters.adtidy.org/extension/ublock/filters/21.txt',
    category: 'tracker',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    subCategory: 'social-trackers',
  },
  {
    id: 'adguard-beacon',
    name: 'AdGuard Analytics & Beacons',
    url: 'https://filters.adtidy.org/extension/ublock/filters/23.txt',
    category: 'tracker',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    subCategory: 'email-tracking',
  },

  // ── PRO listeleri (aboneliğe özel, daha geniş & güncel) ─────────────────────
  {
    id: 'pro-dan-ads',
    name: 'Ads & Tracking Extended (dan)',
    url: 'https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt',
    category: 'ads',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    pro: true,
  },
  {
    id: 'pro-dan-tracking',
    name: 'Tracking Aggressive Extended (dan)',
    url: 'https://www.github.developerdan.com/hosts/lists/tracking-aggressive-extended.txt',
    category: 'tracker',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    pro: true,
  },
  {
    id: 'pro-urlhaus',
    name: 'URLhaus Malware Blocklist',
    url: 'https://urlhaus.abuse.ch/downloads/hostfile/',
    category: 'malware',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    pro: true,
  },
  {
    id: 'pro-phishing-army',
    name: 'Phishing Army Blocklist',
    url: 'https://phishing.army/download/phishing_army_blocklist.txt',
    category: 'phishing',
    enabled: false,
    lastUpdated: null,
    ruleCount: 0,
    cosmeticCount: 0,
    version: null,
    checksum: null,
    sizeBytes: 0,
    builtIn: true,
    pro: true,
  },
];
