# Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.code.style=official

# Compose
android.compose.compiler.metrics=false
android.compose.compilerreports=false

# R8
android.enableR8.fullMode=true

# Suppress compileSdk warning (AGP 8.5.2 tested up to 34, we use 35)
android.suppressUnsupportedCompileSdk=35
