Write-Host "=== k_main.exe CLI test (Run as Administrator) ==="
Write-Host ""
Write-Host "1) Test paket yakalama (sadece sniffer modu, 5sn):"
Write-Host "   .\go-backend\k_main.exe --method=1 --adblock=true --fake=false --global=true"
Write-Host ""
Write-Host "2) Test parametreler:"
Write-Host "   --method=1      (1=split2, 3=split3)"
Write-Host "   --adblock=true   (adblock oku)"
Write-Host "   --fake=false     (MSS yok)"
Write-Host "   --global=true    (TÜM SNI parçala)"
Write-Host ""
Write-Host "3) Sniffer test (Powershell):"
Write-Host "   Start-Process -FilePath '.\go-backend\k_main.exe' -ArgumentList '--method=1','--adblock=true','--fake=false','--global=true' -Verb RunAs"
Write-Host ""
Write-Host "4) Test verisi: basit bir TCP bağlantısı aç (örn. curl, ping, browser)"
Write-Host "   - Recv döngüsü 'yeni akış' / 'parçalanıyor' / 'BAŞARILI' / 'RST' loglar"
Write-Host ""
Write-Host "5) Durum: kapatmak için Ctrl+C (SIGINT)"
Write-Host ""
Write-Host "=== Notlar ==="
Write-Host "• Admin gerekli (WinDivert sürücü düşük seviye filtreleme yapar)"
Write-Host "• blackllist.txt ve adblock_lists/malicious.txt path'leri exe dizinine göre (cwd'ye bağlı)"
Write-Host "• Eğer 'kullanıcı tarafından durduruldu' görürsen: düzeltildi, artık otomatik yeniden başlar"
Write-Host "• engine_state.json cwd'ye yazılır (persist)"
