import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    width: 240,
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    padding: 'var(--space-4) var(--space-3)',
    borderRight: '1px solid var(--glass-border)',
    background: 'linear-gradient(180deg, rgba(15,24,38,0.6), rgba(10,15,28,0.6))',
    backdropFilter: 'var(--glass-blur)',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '0 var(--space-2)',
    marginBottom: 'var(--space-5)',
  },
  logoMark: {
    width: 32,
    height: 32,
    borderRadius: 10,
    background: 'linear-gradient(135deg, var(--accent), var(--accent-strong))',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    fontWeight: 700,
    color: 'var(--text-inverse)',
  },
  brandText: {
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: 0.5,
  },
  list: {
    listStyle: 'none',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    flex: 1,
  },
  item: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 12px',
    borderRadius: 'var(--radius-md)',
    border: 'none',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontSize: 14,
    fontWeight: 500,
    textAlign: 'left',
  },
  itemActive: {
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    boxShadow: 'inset 0 0 0 1px var(--border-accent)',
  },
  itemGlyph: {
    width: 18,
    textAlign: 'center',
    color: 'var(--accent)',
  },
  statusCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderRadius: 'var(--radius-md)',
    background: 'var(--surface-2)',
    border: '1px solid var(--border-subtle)',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  statusText: {
    fontSize: 13,
    fontWeight: 600,
  },
};
